#!/bin/sh

# check that the invoice is for the correct amount
# decoding the invoice with clightning

is_uint() {
    case "$1" in
        ''|*[!0-9]*)
            return 1
        ;;
        *)
            return 0
        ;;
    esac
}

if [ "$#" -lt 2 ]; then
    echo "error: there are not enough parameters" >&2
    exit 1
fi
invoice="$1"
bond_amount="$2"
shift 2

invoice_amount_msat="$(lightning-cli decode "$invoice" | jq -r '.amount_msat')"
if ! is_uint "$invoice_amount_msat"; then
    echo "error: getting invoice amount msat" >&2
    exit 1
fi

invoice_amount="$(echo "scale=0; $invoice_amount_msat / 1000" | bc)"
if ! is_uint "$invoice_amount"; then
    echo "error: getting invoice amount" >&2
    exit 1
fi

if [ "$invoice_amount" -ne "$bond_amount" ]; then
    echo "bond amount: $bond_amount invoice amount: $invoice_amount" >&2
    if [ "$invoice_amount" -gt "$bond_amount" ]; then
        echo "error: invoice amount is too big" >&2
    elif [ "$invoice_amount" -lt "$bond_amount" ]; then
        echo "error: invoice amount is too small" >&2
    fi
    exit 1
fi

# optionally also check if the bond amount is greater than a maximum amount

# maximum_bond_amount="10000000"
# if [ "$invoice_amount" -gt "$maximum_bond_amount" ]; then
#     echo "invoice amount: $invoice_amount maximum amount: $maximum_bond_amount" >&2
#     echo "error: invoice amount is greater than maximum amount" >&2
#     exit 1
# fi

exit 0
