#!/bin/sh

is_uint() {
    case "$1" in
        ''|*[!0-9]*)
            return 1
        ;;
        *)
            return 0
        ;;
    esac
}

if [ "$#" -lt 2 ]; then
    echo "error: there are not enough parameters" >&2
    exit 1
fi
invoice="$1"
bond_amount="$2"
shift 2

invoice_amount_msat="$(lightning-cli decode "$invoice" | jq -r '.amount_msat')"
if ! is_uint "$invoice_amount_msat"; then
    echo "error: getting invoice amount msat" >&2
    exit 1
fi

invoice_amount="$(echo "scale=0; $invoice_amount_msat / 1000" | bc)"
if ! is_uint "$invoice_amount"; then
    echo "error: getting invoice amount" >&2
    exit 1
fi

# bc needs at least a division otherwise scale does not work
maximum_amount="$(echo "scale=0; ($bond_amount * 1.20) / 1" | bc)"
if ! is_uint "$maximum_amount"; then
    echo "error: getting maximum_amount" >&2
    exit 1
fi

if [ "$invoice_amount" -gt "$maximum_amount" ]; then
    echo "error invoice amount is too big" >&2
    exit 1
fi

exit 0
