#!/bin/sh

is_uint() {
    case "$1" in
        ''|*[!0-9]*)
            return 1
        ;;
        *)
            return 0
        ;;
    esac
}

ln_cli() {
    # change if lncli binary is different
    lncli "$@"
}

# check that an invoice is for the correct amount
# decoding the invoice with lnd
lightning_check() {
    if [ "$#" -lt 2 ]; then
        echo "error: there are not enough parameters" >&2
        return 1
    fi
    invoice="$1"
    amount="$2"
    shift 2

    if ! invoice_decode="$(
        ln_cli decodepayreq "$invoice"
    )"; then
        echo "error: decoding invoice" >&2
        return 1
    fi
    if ! invoice_amount="$(
        printf "%s\n" "$invoice_decode" |
        jq -e -r '.num_satoshis'
    )"; then
        echo "error: num satoshis not present in invoice" >&2
        return 1
    fi
    if ! is_uint "$invoice_amount"; then
        echo "error: getting invoice amount" >&2
        return 1
    fi

    if [ "$invoice_amount" -ne "$amount" ]; then
        echo "amount: $amount invoice amount: $invoice_amount" >&2
        if [ "$invoice_amount" -gt "$amount" ]; then
            echo "error: invoice amount is too big" >&2
        elif [ "$invoice_amount" -lt "$amount" ]; then
            echo "error: invoice amount is too small" >&2
        fi
        return 1
    fi

    # optionally also check if the amount is greater than a maximum amount

    # maximum_amount="10000000"
    # if [ "$invoice_amount" -gt "$maximum_amount" ]; then
    #     echo "invoice amount: $invoice_amount maximum amount: $maximum_amount" >&2
    #     echo "error: invoice amount is greater than maximum amount" >&2
    #     return 1
    # fi

    return 0
}

# pay an invoice with lnd
lightning_pay() {
    if [ "$#" -lt 2 ]; then
        echo "error: there are not enough parameters" >&2
        return 1
    fi
    invoice="$1"
    # lnd does not have labels unfortunatly
    # pay_label="$2"
    shift 2

    ln_cli payinvoice \
        --force "$invoice" \
        >&2 &

    echo "$!"
    return 0
}

# generate an invoice with lnd
lightning_invoice() {
    if [ "$#" -lt 2 ]; then
        echo "error: there are not enough parameters" >&2
        return 1
    fi
    amount="$1"
    # lnd does not have labels unfortunatly
    invoice_label="$2"
    shift 2

    if ! invoice_output="$(
        ln_cli addinvoice "$amount"
    )"; then
        echo "error: generating invoice $invoice_label" >&2
        return 1
    fi
    if ! invoice="$(
        printf "%s\n" "$invoice_output" |
        jq -e -r '.pay_req'
    )"; then
        echo "error: invoice not present" >&2
        return 1
    fi

    printf "%s\n" "$invoice"

    return 0
}

if [ "$#" -lt 1 ]; then
    echo "error: insert action" >&2
    return 1
fi
action="$1"
shift 1

case "$action" in
    check)
        lightning_check "$@"
    ;;
    pay)
        lightning_pay "$@"
    ;;
    invoice)
        lightning_invoice "$@"
    ;;
    *)
        echo "error: action $action not available" >&2
        exit 1
    ;;
esac
