#!/bin/sh

# send a notification message with simplex using tor

if [ "$#" -lt 1 ]; then
    echo "error: there are not enough parameters" >&2
    exit 1
fi
message="$1"
shift 1

contact="satoshi-nakamoto"
timeout="32"

simplex-chat -x \
    -e "@${contact} $message" \
    -t "$timeout"
