#!/bin/sh

# send a notification message with simplex using tor

if [ "$#" -lt 2 ]; then
    echo "error: there are not enough parameters" >&2
    exit 1
fi
# event not used
# event="$1"
message="$2"
shift 2

contact="hal-finney"
timeout="64"

simplex-chat -x \
    -e "@${contact} $message" \
    -t "$timeout"
