#!/bin/sh

if [ "$#" -lt 6 ]; then
    echo "error: there are not enough parameters" >&2
    exit 1
fi
invoice="$1"
robot="$2"
order_id="$3"
type_string="$4"
currency="$5"
amount_string="$6"
shift 6

lightning-cli -k pay \
    bolt11="$invoice" \
    label="bond-${robot}-${order_id}-${type_string}-${currency}-${amount_string}" \
    &
